// mock data for unit testing filterAdvocates
export const mockAdvocates = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "New York",
    degree: "MD",
    specialties: [
      "Life coaching",
      "Obsessive-compulsive disorders",
      "Neuropsychological evaluations & testing (ADHD testing)",
      "Attention and Hyperactivity (ADHD)",
    ],
    yearsOfExperience: 10,
    phoneNumber: 5551234567,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    city: "Los Angeles",
    degree: "PhD",
    specialties: [
      "Obsessive-compulsive disorders",
      "Neuropsychological evaluations & testing (ADHD testing)",
      "Attention and Hyperactivity (ADHD)",
      "Sleep issues",
      "Schizophrenia and psychotic disorders",
    ],
    yearsOfExperience: 8,
    phoneNumber: 5559876543,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    city: "Chicago",
    degree: "MSW",
    specialties: [
      "Diabetic Diet and nutrition",
      "Coaching (leadership, career, academic and wellness)",
    ],
    yearsOfExperience: 5,
    phoneNumber: 5554567890,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    city: "Houston",
    degree: "MD",
    specialties: [
      "Chronic pain",
      "Weight loss & nutrition",
      "Eating disorders",
    ],
    yearsOfExperience: 12,
    phoneNumber: 5556543210,
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    city: "Phoenix",
    degree: "PhD",
    specialties: [
      "LGBTQ",
      "Medication/Prescribing",
      "Suicide History/Attempts",
      "General Mental Health (anxiety, depression, stress, grief, life transitions)",
      "Men's issues",
    ],
    yearsOfExperience: 7,
    phoneNumber: 5553210987,
  },
  {
    firstName: "Chris",
    lastName: "Martinez",
    city: "Philadelphia",
    degree: "MSW",
    specialties: [
      "Substance use/abuse",
      "Pediatrics",
      "Women's issues (post-partum, infertility, family planning)",
      "Chronic pain",
      "Weight loss & nutrition",
      "Eating disorders",
      "Diabetic Diet and nutrition",
    ],
    yearsOfExperience: 9,
    phoneNumber: 5557890123,
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    city: "San Antonio",
    degree: "MD",
    specialties: [
      "LGBTQ",
      "Medication/Prescribing",
      "Suicide History/Attempts",
      "General Mental Health (anxiety, depression, stress, grief, life transitions)",
      "Men's issues",
      "Relationship Issues (family, friends, couple, etc)",
      "Trauma & PTSD",
      "Personality disorders",
      "Personal growth",
      "Substance use/abuse",
      "Pediatrics",
      "Women's issues (post-partum, infertility, family planning)",
    ],
    yearsOfExperience: 11,
    phoneNumber: 5554561234,
  },
  {
    firstName: "David",
    lastName: "Harris",
    city: "San Diego",
    degree: "PhD",
    specialties: [
      "LGBTQ",
      "Medication/Prescribing",
      "Suicide History/Attempts",
      "General Mental Health (anxiety, depression, stress, grief, life transitions)",
      "Men's issues",
      "Relationship Issues (family, friends, couple, etc)",
      "Trauma & PTSD",
      "Personality disorders",
      "Personal growth",
      "Substance use/abuse",
      "Pediatrics",
      "Women's issues (post-partum, infertility, family planning)",
      "Chronic pain",
    ],
    yearsOfExperience: 6,
    phoneNumber: 5557896543,
  },
  {
    firstName: "Laura",
    lastName: "Clark",
    city: "Dallas",
    degree: "MSW",
    specialties: ["Attention and Hyperactivity (ADHD)", "Sleep issues"],
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    city: "San Jose",
    degree: "MD",
    specialties: [
      "Personality disorders",
      "Personal growth",
      "Substance use/abuse",
      "Pediatrics",
      "Women's issues (post-partum, infertility, family planning)",
      "Chronic pain",
      "Weight loss & nutrition",
      "Eating disorders",
      "Diabetic Diet and nutrition",
    ],
    yearsOfExperience: 13,
    phoneNumber: 5553217654,
  },
  {
    firstName: "Sarah",
    lastName: "Lee",
    city: "Austin",
    degree: "PhD",
    specialties: [
      "Suicide History/Attempts",
      "General Mental Health (anxiety, depression, stress, grief, life transitions)",
      "Men's issues",
      "Relationship Issues (family, friends, couple, etc)",
      "Trauma & PTSD",
      "Personality disorders",
      "Personal growth",
      "Substance use/abuse",
      "Pediatrics",
      "Women's issues (post-partum, infertility, family planning)",
      "Chronic pain",
      "Weight loss & nutrition",
      "Eating disorders",
      "Diabetic Diet and nutrition",
    ],
    yearsOfExperience: 10,
    phoneNumber: 5551238765,
  },
  {
    firstName: "James",
    lastName: "King",
    city: "Jacksonville",
    degree: "MSW",
    specialties: ["Coaching (leadership, career, academic and wellness)"],
    yearsOfExperience: 5,
    phoneNumber: 5556540987,
  },
  {
    firstName: "Megan",
    lastName: "Green",
    city: "San Francisco",
    degree: "MD",
    specialties: ["Eating disorders", "Diabetic Diet and nutrition"],
    yearsOfExperience: 14,
    phoneNumber: 5559873456,
  },
  {
    firstName: "Joshua",
    lastName: "Walker",
    city: "Columbus",
    degree: "PhD",
    specialties: [
      "Neuropsychological evaluations & testing (ADHD testing)",
      "Attention and Hyperactivity (ADHD)",
    ],
    yearsOfExperience: 9,
    phoneNumber: 5556781234,
  },
  {
    firstName: "Amanda",
    lastName: "Hall",
    city: "Fort Worth",
    degree: "MSW",
    specialties: ["Schizophrenia and psychotic disorders"],
    yearsOfExperience: 3,
    phoneNumber: 5559872345,
  },
];
